### PR TITLE
Fix #4303 radia electron trajectories

### LINKED ISSUE #4303: Add electron trajectories
Add the trajectories calculated by Radia's ```RadFldPtcTrj``` function in both 2d and 3d

### PR DESCRIPTION
**Pull request by mkeilman**
Notes:
- Radia's trajectory function expects the coordinates in a certain order, so we have to rotate both the fields and the input coords, then rotate the output coords back.
- Tested against various dipoles and undulators
- Examples updated

### CODE REVIEW

**Review by gurhar1133 — APPROVED** [review]
Looks good. 

One observation: `extract_report_data()` in template/radia.py is getting really big. Maybe should be broken up into sub calls? eg.
```python
def _geometry_report():
    ...

def _electron_report():
    ...

def extract_report_data(...):
    ...
    PKDict(
        ...
        geometryReport=_geometry_report,
        ...
        electronTrajectoryReport=_electron_report,
        ...
    )[sim_in.report]()
```

**Comment by moellep** [comment]
The new report looks good. I did find that the "Save as SDDS/CSV/SRW" no longer works on this branch for the Field on Path or the other reports on the Visualization page.

**Comment by mkeilman** [comment]
> One observation: `extract_report_data()` in template/radia.py is getting really big. Maybe should be broken up into sub calls? eg.
> 
> ```python
> def _geometry_report():
>     ...
> 
> def _electron_report():
>     ...
> 
> def extract_report_data(...):
>     ...
>     PKDict(
>         ...
>         geometryReport=_geometry_report,
>         ...
>         electronTrajectoryReport=_electron_report,
>         ...
>     )[sim_in.report]()
> ```

Agreed

**Comment by mkeilman** [comment]
> The new report looks good. I did find that the "Save as SDDS/CSV/SRW" no longer works on this branch for the Field on Path or the other reports on the Visualization page.

[966bf43](https://github.com/radiasoft/sirepo/pull/4790/commits/966bf43e9db1fc616aa1bcee29e7501c622637c6)

I'm building the trajectory report download now

**Comment by mkeilman** [comment]
> Looks good - the download works on the reports, except for the Kick Map report for the Undulator example is having this error when download as SDDS (or CSV) is selected:
> 
> ```
> File "sdds.py", line 255, in setColumnValueLists
>     raise Exception(msg)
> Exception: invalid column name xpFactor
> ```

I can't seem to reproduce this error - I tried with a fresh example and it was fine. ???

**Comment by moellep** [comment]
I can't reproduce it with a reset example. Looks good - I'll merge this.

**Pull request merged**
