### PR TITLE
Fix #4334: srw to shadow popup

### LINKED ISSUE #4334: create SRW to Shadow sim avoiding popup blocker
When the SRW to Shadow sim is created, browsers will report a blocked popup. Instead, the process should finish and show a link in the panel to the newly created simulation. Clicking the link should open the Shadow sim in a new browser window.

### PR DESCRIPTION
**Pull request by gurhar1133**
SRW to shadow sim now avoids popup by generating a link in the modal

### CODE REVIEW

**Comment by moellep** [comment]
Looks good. I tried it out and have a few items

Formatting would look better like this:
- buttons aligned right
- Cancel button changes to Close after sim has been created
- x close button in dialog header

Screen Shot 2022-05-26 at 2 47 45 PM

And the results something like this with a clickable link which opens in a new window. Also, if possible, dismiss the dialog when the link is clicked.

Screen Shot 2022-05-26 at 2 51 12 PM

**Comment by moellep** [comment]
Also, each time you select the "Open as a New Shadow Simulation" it should be back in the initial state which allows you to create a totally new sim. Currently it is still showing the dialog with the results link from the previous create.

**Comment by gurhar1133** [comment]
> Looks good. I tried it out and have a few items
> 
> Formatting would look better like this:
> 
> * buttons aligned right
> * Cancel button changes to Close after sim has been created
> * x close button in dialog header
> 
> Screen Shot 2022-05-26 at 2 47 45 PM
> 
> And the results something like this with a clickable link which opens in a new window. Also, if possible, dismiss the dialog when the link is clicked.
> 
> Screen Shot 2022-05-26 at 2 51 12 PM

What do you mean 'dismiss the dialog when the link is clicked'?

**Comment by moellep** [comment]
After you select "Create", you would see the link to the shadow simulation. Clicking the link would open the Shadow simulation in a new window and dismiss the "Open as a New Shadow Simulation" modal in SRW. That way when you return to the browser window with the SRW sim, you don't need to select the Close button.

**Comment by gurhar1133** [comment]
> After you select "Create", you would see the link to the shadow simulation. Clicking the link would open the Shadow simulation in a new window and dismiss the "Open as a New Shadow Simulation" modal in SRW. That way when you return to the browser window with the SRW sim, you don't need to select the Close button.

Gottcha

**Comment by gurhar1133** [comment]
@moellep adding ```data-dismiss="modal"``` attribute to the <a> for the link makes it so the modal closes but then doesn't navigate to the link. Do you have other suggestions for closing the modal when clicking the link?

**Comment by gurhar1133** [comment]
@moellep modal closes now on opening the link

**Comment by moellep** [comment]
Formating and closing the modal looks good.

It still has the problem that you can't invoke the feature multiple times. When I create a new Shadow sim, and then return to the menu item in SRW, it doesn't allow me to create a new Shadow simulation.

**Comment by gurhar1133** [comment]
> Formating and closing the modal looks good.
> 
> It still has the problem that you can't invoke the feature multiple times. When I create a new Shadow sim, and then return to the menu item in SRW, it doesn't allow me to create a new Shadow simulation.

I think I fixed what you are talking about. Take a look and LMK @moellep

**Pull request merged**
