### PR TITLE
fix #4461: add ci-pull-request github action

### LINKED ISSUE #4461: add ci-pull-request github action
Depends on https://github.com/radiasoft/download/issues/225

### PR DESCRIPTION
**Pull request by rorour**
Depends on https://github.com/radiasoft/download/pull/226
Depends on https://github.com/radiasoft/download/issues/234

### CODE REVIEW

**Review by robnagler — APPROVED** [review]
Looks good, but needs to wait for https://github.com/radiasoft/download/pull/226

**Comment by robnagler** [comment]
Depends on #4490

**Comment by robnagler** [comment]
What is the error?

**Comment by rorour** [comment]
```
Jun 22 19:01:15  6220     0 sirepo/uri_router.py:108:call_api api={'base_uri': 'save-moderation-reason', 'cls': <class 'sirepo.auth_role_moderation.API'>, 'decl_uri': '/save-moderation-reason', 'func': <function API.api_saveModerationReason at 0x7faada575d08>, 'func_name': 'api_saveModerationReason', 'name': 'saveModerationReason', 'params': []} exception=All nameservers failed to answer the query 1.0.0.127.in-addr.arpa. IN PTR: Server 168.63.129.16 UDP port 53 answered SERVFAIL stack=Traceback (most recent call last):
  File "/home/runner/work/sirepo/sirepo/sirepo/uri_router.py", line 100, in call_api
    r = flask.make_response(getattr(f.cls(), f.func_name)(**kwargs))
  File "/home/runner/work/sirepo/sirepo/sirepo/auth_role_moderation.py", line 137, in api_saveModerationReason
    ).pkupdate(sirepo.http_request.user_agent_headers())
  File "/home/runner/work/sirepo/sirepo/sirepo/http_request.py", line 184, in user_agent_headers
    domain_name=_dns_reverse_lookup(flask.request.remote_addr),
  File "/home/runner/work/sirepo/sirepo/sirepo/http_request.py", line 177, in _dns_reverse_lookup
    return str(dns.resolver.query(dns.reversename.from_address(ip), 'PTR'))
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/dns/resolver.py", line 1211, in query
    True)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/dns/resolver.py", line 1195, in resolve
    lifetime, search)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/dns/resolver.py", line 1063, in resolve
    (nameserver, port, tcp, backoff) = resolution.next_nameserver()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/dns/resolver.py", line 646, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query 1.0.0.127.in-addr.arpa. IN PTR: Server 168.63.129.16 UDP port 53 answered SERVFAIL
```

**Comment by robnagler** [comment]
We are doing a reverse lookup. Is the exception being caught?

```txt
  File "/home/runner/work/sirepo/sirepo/sirepo/http_request.py", line 177, in _dns_reverse_lookup
    return str(dns.resolver.query(dns.reversename.from_address(ip), 'PTR'))
```

**Comment by robnagler** [comment]
The DNS problem is that 127.0.0.1 is not reverse mapped. We need to handle that in our code.

**Review by robnagler — APPROVED** [review]

**Pull request merged**
