### PR TITLE
Fix #6081 cloudmc 2d tally controls

### LINKED ISSUE #6081: 2d tally plot controls improvements
Some rough edges that need smoothing:

- [x] Make sure the slider controlling the display plane is updated properly. Currently the range and value do not get reset when the axis of the plane changes, for example
- [x] If the slider has a single value in its range, disable it
- [x] Show the units (cm) with the slider value and the min/max fields

### PR DESCRIPTION
**Pull request by mkeilman**
Notes:
- The clipping range boxes are now two-handled sliders courtesy of jQueryUI
- The plane position slider also uses jQueryUI for consistency
- The controls update properly when the axis changes

The layout and labels could use some tweaking. It will also be worthwhile to put the sliders into a custom field, but that can wait to be part of #6132.

Of further note: the jQueryUI javascript file contains *only* the slider and its dependencies (see the [download builder](https://jqueryui.com/download/))

### CODE REVIEW

**Comment by mkeilman** [comment]
Another note: because of the way the aspect ratio works, changing the clip ranges can make the plot change size or distort. We should make a new issue to more intelligently decide the plot size and aspect ratio (probably fix height or width depending on the viewable area).

**Comment by moellep** [comment]
I really like the Plane position widget, but I don't like the Clip options because of the distortion you mentioned and that using the mouse zoom is much more natural. We can have the Clip if you really prefer, but it should be hidden in a sub-option. When the Plane position is changed, it should preserve the current zoom settings, so you can view a section across frames.

The heatmap should show the difference between a missing tally value, and a 0.0 tally value - but this could be opened as a new issue.

**Comment by moellep** [comment]
The heatmap should use the same axes arrangement as the defaults on the 3D plot:
y: x by z (current is z by x)

**Comment by mkeilman** [comment]
> I really like the Plane position widget, but I don't like the Clip options because of the distortion you mentioned and that using the mouse zoom is much more natural. We can have the Clip if you really prefer, but it should be hidden in a sub-option. When the Plane position is changed, it should preserve the current zoom settings, so you can view a section across frames.

Clip was meant to complement zoom for cases where the area of interest is in a small area,  but I'm not rabid for it. I'll remove it.

**Comment by mkeilman** [comment]
To draft while I fix some things

**Comment by mkeilman** [comment]
> The heatmap should show the difference between a missing tally value, and a 0.0 tally value - but this could be opened as a new issue.

Seems pretty involved, as the heatmap has no concept of "don't plot anything here". For that reason ad because it would affect all apps, I agree it should be its own issue.

**Comment by mkeilman** [comment]
Most items addressed; one extra thing I added is to rotate the default 3d view (y axis pointing in, x axis increasing leftt too right) so it matches the 2d view.

I made new issues to omit missing tally values and to preserve zoom when changing slices.

**Pull request merged**
