### PR TITLE
4795 angular distribution

### LINKED ISSUE #4795: angular distribution error
Running the "reactor" simulation with these angular distribution settings causes the simulation to fail with an error: '_generate_angleribution' is not defined

Screen Shot 2022-09-06 at 10 42 57 AM

### PR DESCRIPTION
**Pull request by moellep**
fix #4795 angular distribution corrected
- also implement EnergyFilter, EnergyOutFilter, ParticleFilter code generation

### CODE REVIEW

**Comment by mkeilman** [comment]
I get an error running with energy or energyout filters:
```
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 223, in _do_get_simulation_frame
    msg.data.copy().pkupdate(run_dir=msg.runDir),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 639, in sim_frame_dispatch
    res = o(frame_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/cloudmc.py", line 105, in sim_frame
    :, :, t.get_score_index(frame_args.score)
  File "/home/vagrant/src/radiasoft/openmc/openmc/mesh.py", line 736, in write_data_to_vtk
    volume_normalization=volume_normalization
  File "/home/vagrant/src/radiasoft/openmc/openmc/mesh.py", line 236, in write_data_to_vtk
    raise RuntimeError(errmsg.format(label))
RuntimeError: The size of the dataset mean should be equal to the number of cells
```

**Review by mkeilman — CHANGES_REQUESTED** [review]
Minor comment, but the `write_data_to_vtk()` call fails for energy and energyOut filters

**Comment by moellep** [comment]
The "The size of the dataset mean should be equal to the number of cells" error will happen if you have an EnergyFilter and a MeshFilter on the same tally - the results creates a mesh for every energy step and then it can't convert it correctly. I'll add a better error message in this case.

**Review by mkeilman — APPROVED** [review]
All good - I think disabling or hiding incompatible filters would be a good idea for a future issue

**Pull request merged**
