### PR TITLE
Fix #3129. Enable particle reflection from emitter and collector plates.

### LINKED ISSUE #3129: warpvnd: Enable particle reflection from emitter and collector plates
A common run configuration for our benchmarks are to adjust the reflection properties of the emitter and collector. Currently, the emitter/collector parameters are specified within the “Beam” tab, with no way of specifying reflection.

Screen Shot 2020-11-12 at 11 42 05 AM

Conversely, the additional conductors are explicitly specified within the “Conductor Types” window, and adding a new conductor type enables one to check “Add Reflector”.

Screen Shot 2020-11-12 at 11 39 29 AM

I would like the interface to permit users to specify the emitter and collector as particle reflectors, and choose a diffuse reflection probability as is currently allowed for these other conductors.

Commensurate with this change, I suggest changing the “Beam” tab to be titled “Emitter and Reflector Properties”,
and to list the emitter and reflector explicitly, as is done for the other conductors. This would mean that users won't need to click the "edit" icon in the right corner to view and change the temperature or work function of the cathode and anode.

Of course, the simulation cannot run without the cathode and anode being installed, so these elements do not need to be removable/renamable/movable as the other conductors are, but their temperature, work function, and reflection properties should be listed, and editable by users.

The code to create these conductors is similar to what’s done for the others. Because the emission routines are maintained separately, the specification of temperature/work function/reflectivity does not change the conductor installation procedure. For example, the Python file from the [Gridded TEC 2D Opt](https://www.sirepo.com/warpvnd#/source/alaNGnNc) example specifies on line 200

```python
# Create source conductors 
source_condid = max_c_id + 1 
source = wp.ZPlane(zcent=wp.w3d.zmmin, zsign=-1., voltage=0., condid=source_condid) 
wp.installconductor(source, dfill=wp.largepos)

# Create ground plate
plate_condid = max_c_id + 2
plate = wp.ZPlane(voltage=extractor_voltage, zcent=zplate, condid=plate_condid)
wp.installconductor(plate, dfill=wp.largepos)
scraper = wp.ParticleScraper([source, plate] + conductors, lcollectlpdata=True, lsaveintercept=False)
```

The location/orientation of these collectors (`zcent` and `zsign`) should be fixed and not viewable/editable by users, and they should not be permitted to be labelled as dielectrics.

### PR DESCRIPTION
**Pull request by e-carlin**
I believe this covers everything outlined in #3129. @moellep and @ncook882 I don't know how to verify that these changes are working right. The simulation runs with them but I don't know if it is correct. Lmk if there is something I can do (ex demo, send python sources) to help verify the changes are correct.

@ncook882 this is the new "Emitter and Reflector Properties
Screen Shot 2020-11-13 at 2 41 01 PM
" panel:

When the user double clicks on the cathode or anode on the Conductor Grid they will now be able to adjust the properties of the conductor. Ex for the cathode:
Screen Shot 2020-11-13 at 2 41 12 PM

### CODE REVIEW

**Comment by ncook882** [comment]
@e-carlin thanks very much for the great update. I have a few requests for some text modifications. 

Can you change the "Add Reflector" text to read "Particle Reflector"?

Can you also change the "Emitter and Reflector" panel title to be "Emitter and Collector"?

Can you remove the "Beam X Radius" parameter from the base level panel? It would be fine to keep it in the sub panel that pops up when users select the edit icon.

**Comment by ncook882** [comment]
@e-carlin I have an additional request for adjustments.

Can you make the "Particle Reflector" switch for the cathode and anode available from the "Emitter and Collector Properties" panel? Subsequently, can you make the reflection probabilities accessible from the edit pop-up panel?

Thanks.

**Comment by e-carlin** [comment]
@ncook here are the changes:

Ignore the fields overflowing the border, I'm working on a fix.
Screen Shot 2020-11-16 at 11 02 17 AM

Screen Shot 2020-11-16 at 11 31 47 AM

One question for you, should specular and diffuse reflection probability be editable for cathode, anode, and any user defined elements? Specular probability wasn't editable in any form previously and diffuse probability wasn't editable for the cathode previously.

**Comment by ncook882** [comment]
@e-carlin it would be great if users could specify the reflection probability for all conductor elements that can be reflectors, and especially so for the cathode and anode.

However, a conductor should either a specular or a diffuse reflector (and not both). Would it be possible to make it such that if one of them is specified, then the other is made non-editable? I realize there may be several strategies here, and it's not clear to me which is cleaner/easier from a UI/backend perspective.

**Comment by e-carlin** [comment]
That should be possible. What field controls whether or not the conductor is specular or diffuse?

**Comment by ncook882** [comment]
@e-carlin the reflector WarpVND implementation follows the [`ParticleReflector`](https://github.com/radiasoft/rswarp/blob/master/rswarp/particlecollector/particlereflector.py) class, and the instantiation follows:

```python
 if r['isReflector']:
        reflector = particlereflector.ParticleReflector(scraper=scraper, conductor=c, spref=wp.Species(type=wp.Electron, name='Electron'), srefprob=0., drefprob=r['diffProb'], refscheme='uniform')
        particlereflector.installparticlereflector(reflector)
```

The constructor permits the specification of specular reflection via the `srefprob` argument, and diffuse reflection via the `drefprob` argument. These arguments are templated in the WarpVND data model as `"specProb"` and `"diffProb"`, respectively. 

Technically, the ParticleReflector constructor permits both to be specified at once, so there's no internal check against both being specified. However, it's somewhat unphysical, and adds needless complexity to the simulations, so I'd rather prevent it at the level of the GUI, and permit more advanced users to change it via scripts on their own.

Let me know if this helps.

**Comment by e-carlin** [comment]
@ncook882. User's now have the option to set whether or not the conductor is a specular reflector. Based on whether or not we enable/disable the probability fields.

Screen Shot 2020-11-17 at 10 23 18 AM

**Comment by ncook882** [comment]
This looks great. Thanks very much for making so many updates.

**Comment by e-carlin** [comment]
Sure thing. Thanks for your guidance!

@moellep  ready for your review.

**Comment by moellep** [comment]
I made a few changes, mainly reducing the schema fields (isReflector, isSpecular, specProb, diffProb) into (reflectorType, reflectorProbability). I put the probability values on the main "Emitter and Collector Properties" panel because I thought the multiple toggle buttons were confusing.

Screen Shot 2020-11-17 at 7 49 23 PM

**Pull request merged**
