### PR TITLE
3977 conspicuous undulator panel

### PR DESCRIPTION
**Pull request by gurhar1133**
Now the parameters:
* period
* length
* effective deflecting parameter
Are in the advanced editor panel, and all the others have been moved into the basic editor panel

### CODE REVIEW

**Comment by moellep** [comment]
These values should be on the "basic" panel which is shown on the source page, the other fields should go to the "advanced" panel which is shown in the modal when the pencil is selected:

period
length
effective deflecting parameter

**Comment by gurhar1133** [comment]
> These values should be on the "basic" panel which is shown on the source page, the other fields should go to the "advanced" panel which is shown in the modal when the pencil is selected:
> 
> period length effective deflecting parameter

So are you saying period, length and effective deflecting parameter should be in basic or advanced? Right now they are in advanced: 

Screen Shot 2022-04-15 at 11 22 09 AM

**Comment by moellep** [comment]
Yes, when David said put those fields on the top level panel, he was referring to the basic panel.

**Comment by gurhar1133** [comment]
> Yes, when David said put those fields on the top level panel, he was referring to the basic panel.

But when I showed him that same screenshot he said that's what he wanted: https://github.com/radiasoft/sirepo/issues/3977

**Comment by moellep** [comment]
Yes, but he meant for the basic editor: "Yes, I believe this is the optimal choice for the basic editor panel."

**Comment by gurhar1133** [comment]
> Yes, but he meant for the basic editor: "Yes, I believe this is the optimal choice for the basic editor panel."

@moellep Oh, that makes sense. Thanks for clarifying :) 
Made the change

**Pull request merged**
