### PR TITLE
Fix #3931 better default lastModified and Fix #3937 defer create examples

### LINKED ISSUE #3931: last modified time should not change with a release
I think the fixup that adds last modified time uses "now" instead of the file's mtime.

### LINKED ISSUE #3937: create user needs to login user "earlier"
```txt
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 79, in call_api
    r = flask.make_response(f(**kwargs) if kwargs else f())
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 535, in api_srUnit
    sirepo.auth.login(sirepo.auth.guest, is_mock=True)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/auth/__init__.py", line 252, in login
    uid = create_new_user(lambda u: _login_user(module, u), module)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/auth/__init__.py", line 146, in create_new_user
    u = sirepo.simulation_db.user_create()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 736, in user_create
    uid=uid,
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 834, in _create_lib_and_examples
    save_new_example(s, uid=uid)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 507, in save_new_example
    return save_new_simulation(data, do_validate=False, uid=uid)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 519, in save_new_simulation
    modified=True,
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 541, in save_simulation_json
    data = t.prepare_for_save(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 674, in prepare_for_save
    user_model_list = _load_user_model_list(model_name)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 1707, in _load_user_model_list
    f = _SIM_DATA.lib_file_write_path(_USER_MODEL_LIST_FILENAME[model_name])
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sim_data/__init__.py", line 368, in lib_file_write_path
    return simulation_db.simulation_lib_dir(cls.sim_type()).join(basename)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 639, in simulation_lib_dir
    return simulation_dir(simulation_type, uid=uid).join(_LIB_DIR)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 614, in simulation_dir
    p = user_path(uid) if uid else logged_in_user_path()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 329, in logged_in_user_path
    sirepo.auth.logged_in_user(check_path=False),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/auth/__init__.py", line 196, in logged_in_user
    u,
sirepo.util.SRException: SRException(params=None,routeName=login)
```

Related:
* #3482
* #3931

### PR DESCRIPTION
**Pull request by robnagler**

### CODE REVIEW

**Comment by e-carlin** [comment]
Investigating one problem regarding raydata lib files. Not sure if it is my code or this. Will report back shortly.

**Comment by e-carlin** [comment]
Something is broken with the `package_path` feature and this.

This works:
```
rm -rf run
sirepo service http
# go to raydata, mock analysis, run the simulation on the analysis page
```

This does not work:
```
rm -rf run
SIREPO_FEATURE_CONFIG_PACKAGE_PATH='raydata:sirepo' sirepo service http
# go to raydata, mock analysis, run the simulation on the analysis page
```
I get `Error: Simulation library file "mock-analysis.ipynb" does not exist`

**Comment by e-carlin** [comment]
@robnagler fix is pushed. The simulation_db_test.py is failing for me (before and after change).

```
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/tests/simulation_db_test.py", line 35, in test_last_modified
    t - 10000,
  File "/home/vagrant/src/radiasoft/sirepo/tests/simulation_db_test.py", line 22, in _time
    pkunit.pkeq(t * 1000, data.models.simulation.lastModified)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkunit.py", line 295, in pkeq
    pkfail('expect={} != actual={}', expect, actual)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkunit.py", line 308, in pkfail
    raise PKFail('{} {}'.format(call, msg))
pykern.pkunit.PKFail: tests/simulation_db_test.py:22:_time expect=1636028438000 != actual=1636018438000
```

**Comment by e-carlin** [comment]
@e-carlin there was a case somewhere where we pass an empty string or None to one of these lib_file functions to shortcut the logic and I'm concerned that this change is going to break that. Look into it.

**Comment by robnagler** [comment]
failing for me too :(

**Comment by e-carlin** [comment]
To close the loop on my previous comment. There is a related bug in srw. It is ok not to immediately fix since we don't use package_path with srw https://github.com/radiasoft/sirepo/pull/3940/commits/66d4d2dc6b458b0dd56591a3adb915512a6915f3

**Comment by robnagler** [comment]
I think srw_predefined and pkcli.srw.create_predefined should change. If the file isn't found, the exception needs to be caught, and create_predefined is called.

To find where to write the file in create_predefined, we could look for, say, parameters.py.jinja, and substitute srw_predefined.json, because this is the only write case. Alternatively, we could add a new entry point in sim_data that returns a non-existent file to an appropriate location, e.g. by looking at all dirs in the package.path, and returning the first non-empty dir.

**Comment by robnagler** [comment]
@e-carlin please review

**Review by e-carlin — APPROVED** [review]

**Pull request merged**
