### PR TITLE
Fix #5310 radia align shapes in groups

### LINKED ISSUE #5310: Allow alignment of grouped shapes
Add buttons in the group editor to align the centers or edges of shapes in the group, in each dimension.

### PR DESCRIPTION
**Pull request by mkeilman**
Notes:
- Adds centering and alignment buttons to groups in the object list that appear on hover
- Objects in the group align with the first
- Alignment is done relative to the current coordinate plane (xy, yz, zx)
- Objects cannot belong to multiple groups so the copy button for groups has been removed
- Adds colors to the object list to make it easier to associate with the shapes

### CODE REVIEW

**Comment by moellep** [comment]
I'm not sure if this is an error related to this branch, or a separate issue:

When I select "new simulation", and drag a cuboid and an l-bend onto the grid, and then visit the visualization page, it shows an error notice "Cannot read properties of null (reading 'readout')". Sometimes it works, OK, or sometimes it shows that notice if I'm on the Visualization tab and refresh the browser page.

**Comment by moellep** [comment]
Also, maybe a separate issue:

If I create a group of 2 items and then apply a rotation transform to the group, the group outline rotates, but the subitems do not. When viewed on the Visualization page, the subitems do appear correctly rotated.

**Comment by mkeilman** [comment]
> When I select "new simulation", and drag a cuboid and an l-bend onto the grid, and then visit the visualization page, it shows an error notice "Cannot read properties of null (reading 'readout')". Sometimes it works, OK, or sometimes it shows that notice if I'm on the Visualization tab and refresh the browser page.

See #5483

**Comment by mkeilman** [comment]
> If I create a group of 2 items and then apply a rotation transform to the group, the group outline rotates, but the subitems do not. When viewed on the Visualization page, the subitems do appear correctly rotated.

Yes, separate issue

**Pull request merged**
