### PR TITLE
Fix #5202: rename stateful_compute_compute_column_info to stateful_compute_column_info

### LINKED ISSUE #5202: 20221231 rename "stateful_compute_compute" to just "stateful_compute"
stateful_compute_compute_column_info should be stateful_compute_column_info. The method arg to statefulCompute can simply be column_info. The compute_compute almost looks like a typo.

### PR DESCRIPTION
**Pull request by gurhar1133**
Renamed the methods

### CODE REVIEW

**Comment by robnagler** [comment]
Let's bundle all compute_computes into this one PR:

```
activait.py:def stateful_compute_compute_column_info(data):
rcscon.py:def stateful_compute_compute_column_count(data):
shadow.py:def stateless_compute_compute_harmonic_photon_energy(data):
silas.py:def stateless_compute_compute_rms_size(data):
srw.py:def stateful_compute_compute_undulator_length(data):
srw.py:def stateless_compute_compute_PGM_value(data):
srw.py:def stateless_compute_compute_crl_characteristics(data):
srw.py:def stateless_compute_compute_crystal_init(data):
srw.py:def stateless_compute_compute_crystal_orientation(data):
srw.py:def stateless_compute_compute_delta_atten_characteristics(data):
srw.py:def stateless_compute_compute_dual_characteristics(data):
srw.py:def stateless_compute_compute_grazing_orientation(data):
```

**Comment by moellep** [comment]
I checked and NSLS-II sirepo bluesky does call stateless-compute 'compute_grazing_orientation' so make sure that one remains for backward compatibility.

**Comment by gurhar1133** [comment]
> I checked and NSLS-II sirepo bluesky does call stateless-compute 'compute_grazing_orientation' so make sure that one remains for backward compatibility.

got it

**Comment by gurhar1133** [comment]
changes made @robnagler. lmk if anything else needed

**Review by robnagler — APPROVED** [review]

**Comment by robnagler** [comment]
@gurhar1133 please update the branch

**Comment by gurhar1133** [comment]
> @gurhar1133 please update the branch

oops, sorry i missed that. Will do

**Pull request merged**
