### PR TITLE
ENH: fix crystal diffraction angle to have enum values

### LINKED ISSUE #1345: SRW: enum values for "Diffraction plane angle [rad]" of Crystal
Per @ochubar's request:
> In SRW, "Diffraction plane angle [rad]" can be either 0, +/-Pi/2, or Pi, and it defines horizontal or vertical orientation of beam deflection planes. This has to be fixed in Sirepo (can be a drop-down box like for Miller indices).

We can work on it in person with @ochubar on 9/14.

### PR DESCRIPTION
**Pull request by mrakitin**
Resolves #1345.

### CODE REVIEW

**Comment by mrakitin** [comment]
Still fails with the HXN case:
```py
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 171, in _dispatch
    return _dispatch_call(route.func, kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 181, in _dispatch_call
    resp = flask.make_response(func(**kwargs))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 463, in api_runSimulation
    _start_simulation(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 953, in _start_simulation
    runner.job_start(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/runner.py", line 148, in job_start
    job.start()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/runner.py", line 212, in start
    self.cmd, self.run_dir = simulation_db.prepare_simulation(self.data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 534, in prepare_simulation
    is_parallel=is_p,
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 887, in write_parameters
    _generate_parameters_file(data, run_dir=run_dir)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 1396, in _generate_parameters_file
    _validate_data(data, _SCHEMA)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 1959, in _validate_data
    template_common.validate_models(data, schema)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 332, in validate_models
    validate_model(m, model_schema['model'][m['type']], enum_info)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 301, in validate_model
    '{}: invalid enum "{}" value for field "{}"'.format(item, field_type, k)AssertionError: 1.5707963: invalid enum "DiffractionPlaneAngle" value for field "grazingAngle"
```

**Comment by mrakitin** [comment]
@moellep, any ideas how to properly process the existing simulations with arbitrary values of the diffraction plane angles? Will it be better to create a new `grazingAngleEnum` field for that, and check on the Python side if it does not exist in the model - use the default one?

**Comment by moellep** [comment]
@mrakitin, I think the fixup for existing simulations should check the type() of each crystal.grazingAngle element and if it is a float, then change it to a string and find the closest value to the set. Also, it should convert -1.5707963 to "4.71238898".

**Comment by mrakitin** [comment]
Thanks @moellep! I'll push the update later this week.

**Comment by moellep** [comment]
The crystal.grazingAngle fixup could be something like this. I tried it with the HXN and it looked like it mapped the values correctly.

```
# in def _fixup_beamline(data):
#...
        if item['type'] == 'crystal':
            if isinstance(item['grazingAngle'], (int, float)):
                values = map(lambda x: x[0], _SCHEMA['enum']['DiffractionPlaneAngle'])
                values.append('-1.57079632')
                found = '0'
                for value in values:
                    if re.search(r'^{}'.format(item['grazingAngle']), value):
                        found = value
                        break
                if float(found) < 0:
                    found = '4.71238898'
                item['grazingAngle'] = found
```

This should correctly convert values like 3.14 --> "3.14159265" and -1.57 --> "4.71238898"

**Comment by mrakitin** [comment]
Thanks for the update and merging, @moellep! It was on my plate for a while, but I didn't have a chance to test it in our environment. Hopefully, the fix won't break the existing examples and simulations at NSLS-II.

**Comment by ochubar** [comment]
Maksim, I tested it in a local configuration on my Vagrant VM; it works fine. Thanks for the fix.
HOWEVER: there is still one more related issue there. When one tries to add Height Profile (error) to a Crystal, in the "Height Profile" tab of the "Crystal" dialog, it still takes the values of this unfortunate "Diffraction plane angle" in place of the Grazing Angle, and there is no way to correct this in the GUI. The Grazing Angle has to be calculated from the coordinates of the Tangential vector to the crystal surface, and the "Orientation of Reflection Plane" (hor. or vert.) has to be removed, and the corresponding variable set from the "Diffraction plane angle" discrete value.
Maybe we can try to fix this together, in a local configuration (to have another Sirepo Dev. Demo)?

**Comment by moellep** [comment]
Yes, we can look at it during the meeting tomorrow. Currently it is also updating the "outward normal vector" and "central tangential vector" values when the "diffraction plane angle" is changed. I don't know if that is the correct behavior either.

**Comment by ochubar** [comment]
>Currently it is also updating the "outward normal vector" and "central tangential vector" 
>values when the "diffraction plane angle" is changed.

Yes, this is the correct behavior (and the updated values seem to be correct, but we may need to re-check this).

**Comment by moellep** [comment]
@ochubar, I think I understand the problem now. When auto-computing the crystal grazing angle, you mention using the tangential vector. 

As an example, in the SRX crystal C1, the normal vector is (-0.9689738178863608, 6.584077004e-9) and the tangential is (-0.24716338776349875, 1.67944969e-9). For a mirror, it looks like I could take the arcsin() of the primary tangential vector value to get the grazing angle. Is this the step to get the grazing angle from the crystal as well?

**Comment by ochubar** [comment]
More generally, the grazing angle can be expressed as: arccos(tz) = arccos(sqrt(1 - tx^2 - ty^2)), where tz is the longitudinal component of the tangential vector and tx and ty are its horizontal and vertical components respectively (tx=-0.24716338776349875, ty=1.67944969e-9 in your example). This applies both to mirrors and crystals (in the case of crystals, this grazing angle is actually equal to the Bragg angle).

**Comment by moellep** [comment]
Thanks @ochubar! I've made a fix with 87f3233 which keeps the crystal diffraction angle and grazing angle separate and computes the grazing angle from the tangential vector when needed. The NSLS-II SMI  example now runs with the correct grazing angle and can have a profile file assigned to both crystals.

**Pull request merged**
