### PR TITLE
Fix #6525: save subsims on import

### LINKED ISSUE #6525: omega zip export

### PR DESCRIPTION
**Pull request by gurhar1133**
Importing an exported zip now calls copy_related_sims in same way link sharing does

### CODE REVIEW

**Review by moellep — CHANGES_REQUESTED** [review]
This implementation works if the export is created and imported on the same system, but wouldn't work across systems (alpha to beta). The export file needs to collect all the related sims and keep them in the zip file, and when imported, it should create the sims, rather than expect the sim id to still be present on the system.

**Comment by gurhar1133** [comment]
> This implementation works if the export is created and imported on the same system, but wouldn't work across systems (alpha to beta). The export file needs to collect all the related sims and keep them in the zip file, and when imported, it should create the sims, rather than expect the sim id to still be present on the system.

Do we have this problem for link sharing too?

**Comment by moellep** [comment]
Link sharing works correctly because it is always on the same system.

**Comment by gurhar1133** [comment]
another look @moellep ?

**Review by moellep — APPROVED** [review]

**Pull request merged**
