### PR TITLE
Fix #6003 #5976 wavelength, frequency and amplifier tab refactor

### LINKED ISSUE #6003: Add longitudinal representation of wavelength and frequency

### PR DESCRIPTION
**Pull request by gurhar1133**
Added longitudinal wavelength and frequency plots as well as refactored the `_laser_pulse_plot()` function to use a class

### CODE REVIEW

**Comment by moellep** [comment]
I'm seeing server errors when selecting Total Intensity or Total Phase on the Laser Pulse tab on this branch.

**Comment by gurhar1133** [comment]
@moellep can you try again? I think this is fixed

**Comment by moellep** [comment]
This PR looks good - @gurhar1133 is there an example notebook where wavelength and frequency are plotted? In the current silas examples, they are pretty flat graphs.

**Comment by gurhar1133** [comment]
> This PR looks good - @gurhar1133 is there an example notebook where wavelength and frequency are plotted? In the current silas examples, they are pretty flat graphs.

I'll take a look at examples
Screenshot 2023-07-17 at 3 53 58 PM

But also, on multi-pass example the wavelength and frequency aren't flat

**Comment by moellep** [comment]
They are both essentially flat - the offset is shown in the upper left.
The first one has values between 8.0002e-07 and 7.9998e-07 and the second one is between 374735000000000.0 374745000000000.0.

**Comment by gurhar1133** [comment]
> They are both essentially flat - the offset is shown in the upper left. The first one has values between 8.0002e-07 and 7.9998e-07 and the second one is between 374735000000000.0 374745000000000.0.

Oops. Yes, good point

**Pull request merged**
