### PR TITLE
Fix #5994: make etc/run-jupyterhub.sh work again

### LINKED ISSUE #5994: `bash etc/run-jupyterhub` not working
Looks like `serverextension` is no longer a valid command. In addition, jupyterhub_debug was removed in bffb3215706f5b0d05a4c8e7720c03515804cefc .

### PR DESCRIPTION
**Pull request by e-carlin**
- notebook must now be installed explicitly
- serverextension call is no longer needed with the version of notebook we install
- jupyterhub_debug was removed in favor of feature_config.debug but this needed to be cascaded in the jupyterhub conf jinja

### CODE REVIEW

**Comment by e-carlin** [comment]
@rorour ping

**Comment by rorour** [comment]
Not working for me. I keep getting "error: jupyterlab-server: not installed run `pip install jupyterlab-server==2.8.2`" which i've already run. Here is the full output.

```
[py3;@v sirepo]$ bash etc/run-jupyterhub.sh
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2023/06/26 20:21:35 [warn] 242217#242217: could not build optimal types_hash, you should increase either types_hash_max_size: 2048 or types_hash_bucket_size: 64; ignoring types_hash_bucket_size
2023/06/26 20:21:35 [notice] 242217#242217: using the "epoll" event method
2023/06/26 20:21:35 [notice] 242217#242217: nginx/1.24.0
2023/06/26 20:21:35 [notice] 242217#242217: OS: Linux 6.2.10-100.fc36.x86_64
2023/06/26 20:21:35 [notice] 242217#242217: getrlimit(RLIMIT_NOFILE): 1024:524288
2023/06/26 20:21:35 [notice] 242217#242217: start worker processes
2023/06/26 20:21:35 [notice] 242217#242217: start worker process 242218
sirepo/job_driver/__init__.py:408:init_module modules=['local']
sirepo/pkcli/job_supervisor.py:82:default_command ip=127.0.0.1 port=8001
sirepo/pkcli/service.py:241:tornado ip=0.0.0.0 port=8000
error: jupyterlab-server: not installed run `pip install jupyterlab-server==2.8.2`
etc/run-jupyterhub.sh: line 1: kill: (242027) - No such process
2023/06/26 20:21:36 [notice] 242217#242217: signal 15 (SIGTERM) received from 242025, exiting
2023/06/26 20:21:36 [notice] 242218#242218: exiting
2023/06/26 20:21:36 [notice] 242218#242218: exit
2023/06/26 20:21:36 [notice] 242217#242217: signal 17 (SIGCHLD) received from 242218
2023/06/26 20:21:36 [notice] 242217#242217: worker process 242218 exited with code 0
2023/06/26 20:21:36 [notice] 242217#242217: exit
```

**Comment by e-carlin** [comment]
Sorry, I had a fix but forgot to push. Try now.

**Comment by rorour** [comment]
Thanks. I'm now running into this- should i run `npm install -g configurable-http-proxy`?

```
[D 2023-06-26 20:30:05.501 JupyterHub proxy:704] Proxy cmd: ['configurable-http-proxy', '--ip', '127.0.0.1', '--port', '8002', '--api-ip', '127.0.0.1', '--api-port', '8111', '--error-target', 'http://127.0.0.1:8081/jupyter/hub/error', '--log-level', 'debug']
[E 2023-06-26 20:30:05.505 JupyterHub proxy:711] Failed to find proxy ['configurable-http-proxy']
    The proxy can be installed with `npm install -g configurable-http-proxy`.To install `npm`, install nodejs which includes `npm`.If you see an `EACCES` error or permissions error, refer to the `npm` documentation on How To Prevent Permissions Errors.
```

**Comment by e-carlin** [comment]
Yes but realizing how this works now I think it is goofy to make the user install all deps. I'm going to move the install into `etc/run-jupyterhub.sh`. I'll report back when done.

**Comment by e-carlin** [comment]
https://github.com/radiasoft/sirepo/pull/5995/commits/c34fddf2d75806c66479f6a2a997a822e324b0b0 Deps are now installed for you. Please try again.

**Pull request merged**
