### PR TITLE
SRW: fix missing mirror profile file

### PR DESCRIPTION
**Pull request by mrakitin**
This PR fixed testing for existence of the mirror profile file.

Should we raise if the file is not found or just silently proceed with calculation?

### CODE REVIEW

**Comment by bruhwiler** [comment]
I think if a file is expected, but not found, then the calculation should stop and the user should be notified.

**Comment by moellep** [comment]
This issue came up when mrakitin was demoing running sirepo SRW generated source in a jupyter notebook. The original SRW simulation required a mirror error file, and crashed the jupyter notebook when it was missing. I'll merge this pull request and change it so it shows a better error message in this case. It shouldn't ignore the error, or the user may wonder why the simulation results were different in the notebook compared with the original simulation.

**Comment by mrakitin** [comment]
Thanks @bruhwiler and @moellep for your feedback. Yes, I agree the simulation should not proceed without the required files, but the error should be more user-friendly (ideally testing that file exists and raising should be done at SRW side).

**Comment by moellep** [comment]
I've checked in a change now, and the generate code is similar to this:

>     ifnElMirror1 = "mirror_2d.dat"
>     if ifnElMirror1:
>         assert os.path.isfile(ifnElMirror1), "Missing input file mirror_2d.dat, required by Elliptical Cylinderx beamline element"
>         hProfDataElMirror1 = srwlib.srwl_uti_read_data_cols(ifnElMirror1, "\t")
>

**Comment by mrakitin** [comment]
Great, thanks @moellep! For history: https://github.com/radiasoft/sirepo/commit/ec2d2a456744c815d841cc6a2f135a1c0f9a8995. I hope `Cylinderx` is a typo in your example, I don't see that extra `x` in the code.

**Comment by moellep** [comment]
The "Elliptical Cylinderx" was the name of my beamline element in my test simulation. The generated code would include whatever title the beamline element was given.

**Comment by mrakitin** [comment]
Great, I see, thanks!

**Pull request merged**
